# Generated by Django 3.1.3 on 2020-11-25 06:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, choices=[('Steel Trough Roller', 'Steel Trough Roller'), ('Steel Return Roller', 'Steel Return Roller'), ('HDPE Trough Roller', 'HDPE Trough Roller'), ('HDPE Return Roller', 'HDPE Return Roller'), ('Impact Roller', 'Impact Roller')], default='Steel Trough Roller', max_length=50, null=True)),
                ('roller_diameter', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('wall_thickness', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('roller_length', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('shaft_diameter', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('bearing', models.CharField(blank=True, max_length=100, null=True)),
                ('aud', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('usd', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-description',),
            },
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('vendor_status', models.CharField(blank=True, max_length=200, null=True)),
                ('sp_type', models.CharField(blank=True, choices=[('ground engaging tools', 'ground engaging tools'), ('manganese liners', 'manganese liners'), ('mechanical parts', 'mechanical parts')], default='mechanical parts', max_length=50, null=True)),
                ('weight_kg', models.CharField(blank=True, max_length=50, null=True)),
                ('machine', models.CharField(blank=True, max_length=50, null=True)),
                ('model_number', models.CharField(blank=True, max_length=50, null=True)),
                ('aud', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('usd', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-vendor_status',),
            },
        ),
        migrations.CreateModel(
            name='Local_Comparison_SparePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=250, null=True)),
                ('vendor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('vendor_status', models.CharField(blank=True, max_length=50, null=True)),
                ('sp_type', models.CharField(blank=True, choices=[('ground engaging tools', 'ground engaging tools'), ('manganese liners', 'manganese liners'), ('mechanical parts', 'mechanical parts')], default='mechanical parts', max_length=50, null=True)),
                ('weight_kg', models.CharField(blank=True, max_length=50, null=True)),
                ('machine', models.CharField(blank=True, max_length=50, null=True)),
                ('model_number', models.CharField(blank=True, max_length=50, null=True)),
                ('aud', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('usd', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('part_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_parts', to='spareparts.sparepart')),
            ],
            options={
                'ordering': ('-vendor_status',),
            },
        ),
    ]
