# Generated by Django 3.1.3 on 2020-11-26 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spareparts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='local_comparison_sparepart',
            name='part_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison_sparepart', to='spareparts.sparepart'),
        ),
    ]
