# Generated by Django 3.1.3 on 2020-11-25 09:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=250)),
                ('state', models.CharField(choices=[('ACT', 'ACT'), ('QLD', 'QLD'), ('NSW', 'NSW'), ('SA', 'SA'), ('VIC', 'VIC'), ('TAS', 'TAS')], default='VIC', max_length=10)),
                ('manager_name', models.CharField(blank=True, max_length=50, null=True)),
                ('manager_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('manager_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('supervisor_name', models.CharField(blank=True, max_length=50, null=True)),
                ('supervisor_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('supervisor_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
